str1='hello world'
print(str1.lower())
print(str1.upper())
print(str1.capitalize())
print(str1.title())
print(str1.swapcase())
print(str1.swapcase())
print(str1.isalnum())
print(len(str1))
print(str1.count('o'))
print(str1.find('o'))
